version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  reviewers:
  - interactivellama
  assignees:
  - interactivellama
  labels:
  - maintenance-task
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: find-remove
    versions:
    - 2.0.3
    - 3.0.1
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.15
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.11
    - 7.13.12
    - 7.13.13
    - 7.13.15
    - 7.13.4
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: react-modal
    versions:
    - 3.12.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: "@salesforce-ux/icons"
    versions:
    - 9.39.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
